const cabmock = [
    {
        id: 1,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '12,000원',
        yesterdayIntake: '1,100kg',
        todayPrice: '12,865원',
        tomorrowPrice: '13,063원',
        grade: 'high',
        priceDiff: 865,
        priceRate: 7.2
    },
    {
        id: 2,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '12,865원',
        yesterdayIntake: '1,100kg',
        todayPrice: '13,708원',
        tomorrowPrice: '13,911원',
        grade: 'high',
        priceDiff: 843,
        priceRate: 6.6
    },
    {
        id: 3,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '13,708원',
        yesterdayIntake: '1,100kg',
        todayPrice: '14,406원',
        tomorrowPrice: '14,532원',
        grade: 'high',
        priceDiff: 698,
        priceRate: 5.1
    },
    {
        id: 4,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '14,406원',
        yesterdayIntake: '1,100kg',
        todayPrice: '14,531원',
        tomorrowPrice: '14,778원',
        grade: 'high',
        priceDiff: 125,
        priceRate: 0.9
    },
    {
        id: 5,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '14,531원',
        yesterdayIntake: '1,100kg',
        todayPrice: '14,797원',
        tomorrowPrice: '15,014원',
        grade: 'high',
        priceDiff: 266,
        priceRate: 1.8
    },
    {
        id: 6,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '14,797원',
        yesterdayIntake: '1,100kg',
        todayPrice: '14,903원',
        tomorrowPrice: '15,100원',
        grade: 'high',
        priceDiff: 106,
        priceRate: 0.7
    },
    {
        id: 7,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '14,903원',
        yesterdayIntake: '1,100kg',
        todayPrice: '15,691원',
        tomorrowPrice: '15,801원',
        grade: 'high',
        priceDiff: 788,
        priceRate: 5.3
    },
    {
        id: 8,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '15,691원',
        yesterdayIntake: '1,100kg',
        todayPrice: '15,599원',
        tomorrowPrice: '15,982원',
        grade: 'high',
        priceDiff: -92,
        priceRate: -0.6
    },
    {
        id: 9,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '15,599원',
        yesterdayIntake: '1,100kg',
        todayPrice: '16,571원',
        tomorrowPrice: '16,802원',
        grade: 'high',
        priceDiff: 972,
        priceRate: 6.2
    },
    {
        id: 10,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '16,571원',
        yesterdayIntake: '1,100kg',
        todayPrice: '16,426원',
        tomorrowPrice: '16,545원',
        grade: 'high',
        priceDiff: -145,
        priceRate: -0.9
    },
    {
        id: 11,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '16,426원',
        yesterdayIntake: '1,100kg',
        todayPrice: '17,128원',
        tomorrowPrice: '17,381원',
        grade: 'high',
        priceDiff: 702,
        priceRate: 4.3
    },
    {
        id: 12,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '17,128원',
        yesterdayIntake: '1,100kg',
        todayPrice: '17,424원',
        tomorrowPrice: '17,648원',
        grade: 'high',
        priceDiff: 296,
        priceRate: 1.7
    },
    {
        id: 13,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '17,424원',
        yesterdayIntake: '1,100kg',
        todayPrice: '18,068원',
        tomorrowPrice: '18,221원',
        grade: 'high',
        priceDiff: 644,
        priceRate: 3.7
    },
    {
        id: 14,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '18,068원',
        yesterdayIntake: '1,100kg',
        todayPrice: '18,730원',
        tomorrowPrice: '19,125원',
        grade: 'high',
        priceDiff: 662,
        priceRate: 3.7
    },
    {
        id: 15,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '18,730원',
        yesterdayIntake: '1,100kg',
        todayPrice: '18,594원',
        tomorrowPrice: '18,721원',
        grade: 'high',
        priceDiff: -136,
        priceRate: -0.7
    },
    {
        id: 16,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '18,594원',
        yesterdayIntake: '1,100kg',
        todayPrice: '19,220원',
        tomorrowPrice: '19,479원',
        grade: 'high',
        priceDiff: 626,
        priceRate: 3.4
    },
    {
        id: 17,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '19,220원',
        yesterdayIntake: '1,100kg',
        todayPrice: '20,171원',
        tomorrowPrice: '20,385원',
        grade: 'high',
        priceDiff: 951,
        priceRate: 4.9
    },
    {
        id: 18,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '20,171원',
        yesterdayIntake: '1,100kg',
        todayPrice: '20,467원',
        tomorrowPrice: '20,865원',
        grade: 'high',
        priceDiff: 296,
        priceRate: 1.5
    },
    {
        id: 19,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '20,467원',
        yesterdayIntake: '1,100kg',
        todayPrice: '20,561원',
        tomorrowPrice: '20,789원',
        grade: 'high',
        priceDiff: 94,
        priceRate: 0.5
    },
    {
        id: 20,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '20,561원',
        yesterdayIntake: '1,100kg',
        todayPrice: '21,450원',
        tomorrowPrice: '21,757원',
        grade: 'high',
        priceDiff: 889,
        priceRate: 4.3
    },
    {
        id: 21,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '21,450원',
        yesterdayIntake: '1,100kg',
        todayPrice: '21,916원',
        tomorrowPrice: '22,048원',
        grade: 'high',
        priceDiff: 466,
        priceRate: 2.2
    },
    {
        id: 22,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '21,916원',
        yesterdayIntake: '1,100kg',
        todayPrice: '22,079원',
        tomorrowPrice: '22,205원',
        grade: 'high',
        priceDiff: 163,
        priceRate: 0.7
    },
    {
        id: 23,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '22,079원',
        yesterdayIntake: '1,100kg',
        todayPrice: '22,754원',
        tomorrowPrice: '23,144원',
        grade: 'high',
        priceDiff: 675,
        priceRate: 3.1
    },
    {
        id: 24,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '22,754원',
        yesterdayIntake: '1,100kg',
        todayPrice: '23,446원',
        tomorrowPrice: '23,642원',
        grade: 'high',
        priceDiff: 692,
        priceRate: 3.0
    },
    {
        id: 25,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '23,446원',
        yesterdayIntake: '1,100kg',
        todayPrice: '23,912원',
        tomorrowPrice: '24,049원',
        grade: 'high',
        priceDiff: 466,
        priceRate: 2.0
    },
    {
        id: 26,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '23,912원',
        yesterdayIntake: '1,100kg',
        todayPrice: '24,090원',
        tomorrowPrice: '24,295원',
        grade: 'high',
        priceDiff: 178,
        priceRate: 0.7
    },
    {
        id: 27,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '24,090원',
        yesterdayIntake: '1,100kg',
        todayPrice: '24,462원',
        tomorrowPrice: '24,750원',
        grade: 'high',
        priceDiff: 372,
        priceRate: 1.5
    },
    {
        id: 28,
        name: '배추',
        unit: '포기',
        yesterdayPrice: '24,462원',
        yesterdayIntake: '1,100kg',
        todayPrice: '25,425원',
        tomorrowPrice: '25,698원',
        grade: 'high',
        priceDiff: 963,
        priceRate: 3.9
    }
];

export default cabmock;